openapi: 3.0.0
info:
  title: Physical AI Book Content API
  description: API for accessing and managing content for the Physical AI and Humanoid Robotics book
  version: 1.0.0

paths:
  /chapters:
    get:
      summary: List all chapters
      description: Retrieve a list of all available chapters in the book
      responses:
        '200':
          description: A list of chapters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Chapter'

  /chapters/{id}:
    get:
      summary: Get a specific chapter
      description: Retrieve detailed information about a specific chapter
      parameters:
        - name: id
          in: path
          required: true
          description: Chapter identifier
          schema:
            type: string
      responses:
        '200':
          description: Detailed chapter information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chapter'
        '404':
          description: Chapter not found

  /exercises/{chapterId}:
    get:
      summary: Get exercises for a chapter
      description: Retrieve all exercises associated with a specific chapter
      parameters:
        - name: chapterId
          in: path
          required: true
          description: Chapter identifier
          schema:
            type: string
      responses:
        '200':
          description: List of exercises for the chapter
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Exercise'

components:
  schemas:
    Chapter:
      type: object
      required:
        - id
        - title
        - content
        - level
      properties:
        id:
          type: string
          description: Unique identifier for the chapter
        title:
          type: string
          description: Title of the chapter
        content:
          type: string
          description: Markdown content of the chapter
        description:
          type: string
          description: Brief description of the chapter
        level:
          type: string
          enum: [beginner, intermediate, advanced]
          description: Difficulty level of the chapter
        examples:
          type: array
          items:
            $ref: '#/components/schemas/Example'
        exercises:
          type: array
          items:
            $ref: '#/components/schemas/Exercise'
        learningObjectives:
          type: array
          items:
            type: string
          description: List of learning objectives for the chapter

    Example:
      type: object
      required:
        - id
        - title
        - code
      properties:
        id:
          type: string
          description: Unique identifier for the example
        title:
          type: string
          description: Title of the example
        description:
          type: string
          description: What the example demonstrates
        code:
          type: string
          description: Code snippet for the example
        explanation:
          type: string
          description: Detailed explanation of the example

    Exercise:
      type: object
      required:
        - id
        - title
        - description
      properties:
        id:
          type: string
          description: Unique identifier for the exercise
        title:
          type: string
          description: Title of the exercise
        description:
          type: string
          description: What students need to do
        instructions:
          type: string
          description: Step-by-step instructions
        starterCode:
          type: string
          description: Optional starter code for the exercise
        solution:
          type: string
          description: Reference solution
        difficulty:
          type: string
          enum: [easy, medium, hard]
          description: Difficulty level of the exercise