[project]
name = "secure-data-encryption-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=44.0.2",
    "fernet>=1.0.1",
    "streamlit>=1.44.1",
]
